server:
  port: 9999

spring:
  application:
    name: gateway



  cloud:
    discovery:
      enabled: true

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE